/*
 * Copyright (c) 2023 chocopoi
 * 
 * This file is part of DressingTools.
 * 
 * DressingTools is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * 
 * DressingTools is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with DressingTools. If not, see <https://www.gnu.org/licenses/>.
 */

using System;

namespace Chocopoi.DressingTools.OneConf.Wearable.Modules.BuiltIn.ArmatureMapping
{
    /// <summary>
    /// Bone mapping mode
    /// </summary>
    [Serializable]
    internal enum BoneMappingMode
    {
        /// <summary>
        /// Auto mode. Bone mappings are all generated by dresser.
        /// </summary>
        Auto = 0,

        /// <summary>
        /// Override mode. Bone mappings are generated by dresser and overrided by user mappings on top.
        /// </summary>
        Override = 1,

        /// <summary>
        /// Manual mode. Only user mappings are used.
        /// </summary>
        Manual = 2
    }
}
