name: dotnet-format

on:
  push:
    paths:
      - "**.cs"
      - ".editorconfig"
      - ".github/workflows/format-check.yml"

jobs:
  check-format:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format

      - name: Check out code
        uses: actions/checkout@v4

      - name: Run dotnet format
        run: dotnet format whitespace "./" --exclude .github docs~ logo~ --folder --verify-no-changes --verbosity diagnostic
